local_backend: true

backend:
  name: github
  repo: AntonTat27/sharmony-landing
  branch: dev # or main â€” whichever you want Decap to commit to
  auth_type: implicit
  base_url: https://api.github.com
  app_id: Ov23lij5CmVSkQgQbaLV

media_folder: "static/uploads"
public_folder: "/uploads"

i18n:
  structure: multiple_folders
  locales: [en, ru, de, fr] # all languages
  default_locale: en

collections:
  - name: "menu_translations"
    label: "Menu Translations"
    folder: "data" # Root folder
    i18n: true # Enable the language switcher
    extension: "toml"
    format: "toml"
    identifier_field: "id"
    # This matches your working content structure: data/en/menu.toml
    path: "{{locale}}/menu"
    fields:
      - label: "Items"
        name: "items"
        widget: "list"
        i18n: true
        fields:
          - { label: "ID", name: "id", widget: "string" }
          - { label: "Text", name: "text", widget: "string", i18n: true }

  - name: "Sharmony Header Page"
    label: "Header Page"
    folder: "content" # The root folder
    i18n: true # Enable the i18n switcher
    create: false # Important: Stops users from making random files
    extension: "md"
    format: "frontmatter"
    filter: { field: "type", value: "header" }
    path: "{{locale}}"
    fields:
      - {
          label: "Banner Text",
          name: "banner_text",
          widget: "string",
          i18n: true,
        }
      - {
          label: "Banner CTA",
          name: "banner_cta",
          widget: "string",
          i18n: true,
        }

  - name: "Sharmony Main Page"
    label: "Main Page"
    folder: "content" # The root folder
    i18n: true # Enable the i18n switcher
    create: false # Important: Stops users from making random files
    extension: "md"
    format: "frontmatter"
    filter: { field: "type", value: "mainpage" }
    path: "{{locale}}"
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - {
          label: "Main Intro H1",
          name: "main_intro_h1",
          widget: "string",
          i18n: true,
        }
      - {
          label: "Main Intro H2",
          name: "main_intro_h2",
          widget: "string",
          i18n: true,
        }

  - name: "Sharmony Investor"
    label: "Investor Page"
    folder: "content" # The root folder
    i18n: true # Enable the i18n switcher
    create: false # Important: Stops users from making random files
    extension: "md"
    format: "frontmatter"
    filter: { field: "type", value: "investor" }
    path: "{{locale}}"
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }

  - name: "Sharmony Partners"
    label: "Partners Page"
    folder: "content" # The root folder
    i18n: true # Enable the i18n switcher
    create: false # Important: Stops users from making random files
    extension: "md"
    format: "frontmatter"
    filter: { field: "type", value: "partners" }
    path: "{{locale}}"
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }

  - name: "Sharmony Marketplace"
    label: "Marketplace Page"
    folder: "content" # The root folder
    i18n: true # Enable the i18n switcher
    create: false # Important: Stops users from making random files
    extension: "md"
    format: "frontmatter"
    filter: { field: "type", value: "marketplace" }
    path: "{{locale}}"
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }

  - name: "Sharmony Wallet"
    label: "Wallet Page"
    folder: "content" # The root folder
    i18n: true # Enable the i18n switcher
    create: false # Important: Stops users from making random files
    extension: "md"
    format: "frontmatter"
    filter: { field: "type", value: "wallet" }
    path: "{{locale}}"
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
